
title: The Boulder Guitar Society
description: >-
   The Boulder Guitar Society promotes the teaching, learning,
   performance and enjoyment of classical and fingerstyle guitar.
TZ: America/Denver
url: "https://boulderguitarsociety.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
