
title: The Boulder Guitar Society
description: >-
   The Boulder Guitar Society fosters and promotes the teaching, learning,
   enjoyment and performance experience of guitar music with an emphasis
   on classical and fingerstyle guitar.
TZ: America/Denver
url: "https://boulderguitarsociety.github.io"
plugins:
  - jekyll-sitemap
