
title: The Boulder Guitar Society
description: >-
   The Boulder Guitar Society promotes the teaching, learning,
   performance and enjoyment of classical and fingerstyle guitar.
TZ: America/Denver
url: "https://boulderguitarsociety.github.io"
image:
   path: /favicon.png
   height: 192
   width: 192
   alt: BGS Logo
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-seo-tag
